grid_map_pcl:
  ros__parameters:
    input_pointcloud_topic: "/susag/depth/depth_camera/points"
    base_frame: "base_link"
    map_frame: "odom"      # set RViz Fixed Frame = odom
    resolution: 0.05
    min_x: -6.0
    max_x: 6.0
    min_y: -6.0
    max_y: 6.0
    min_z: -2.0
    max_z: 2.0
    voxel_size: 0.05
    remove_outliers: true
    outlier_mean_k: 16
    outlier_stddev_mul: 1.0
    use_median_height: true
    raycasting: false
    output_grid_map_topic: "/elevation_map"
    elevation_layer_name: "elevation"
