grid_map_visualization:
  ros__parameters:
    grid_map_topic: "/elevation_map"
    visualization:
      - name: "elevation_points"
        type: "point_cloud"
        params: { layer: "elevation" }
      - name: "elevation_colored"
        type: "grid_map"
        params: { layer: "elevation", coloring_layer: "elevation" }
