from launch_ros.actions import Node
from launch.actions import DeclareLaunchArgument
from launch_ros.substitutions import FindPackageShare
from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import PathJoinSubstitution
from launch.substitutions import LaunchConfiguration, TextSubstitution
from launch.conditions import IfCondition
import os
import xacro
from ament_index_python.packages import get_package_share_directory


# BARN dataset lives in src/ as plain data (not an installed package).
# 1:1 is the thesis scale: every sandbox result is at scale 1.0, and at x1.2
# all 300 BARN worlds become "comfortable" for the 0.84 x 0.68 m footprint
# (see BARN_dataset/scaled_1.2/susag_suitable_worlds.txt), so the narrow-
# environment claim cannot be tested there. `scaled_1` is the 1:1 geometry
# regenerated by scale_barn.py: identical obstacle poses, plus sealed lateral
# walls and planner-padded maps that the raw dataset lacks.
BARN_SCALE = 1.0
BARN_WORLDS_DIR = (
    f'/home/saran/robohouse_ws/src/BARN_dataset/scaled_{BARN_SCALE:g}/world_files'
)

# BARN corridor geometry (verified against grid_files):
#   corridor x in [-4.5, 0], travel direction +y
#   obstacle field cell (row, col) -> x = row*0.15 - 4.425, y = col*0.15 + 5.175
#   free spawn zone y in [0, 5.17]; field exit at y = 9.53
# Default spawn: corridor centre, facing +y.


def generate_launch_description():
    share_dir = get_package_share_directory('susag_updated_model_description')

    xacro_file = os.path.join(share_dir, 'urdf', 'susag_updated_model.xacro')
    robot_description_config = xacro.process_file(xacro_file)
    use_sim_time = LaunchConfiguration('use_sim_time', default='true')
    robot_urdf = robot_description_config.toxml()

    world_idx = LaunchConfiguration('world_idx', default='0')
    worlds_dir = LaunchConfiguration('worlds_dir', default=BARN_WORLDS_DIR)
    x_pose = LaunchConfiguration('x_pose', default=f'{-2.25 * BARN_SCALE:g}')
    y_pose = LaunchConfiguration('y_pose', default=f'{1.0 * BARN_SCALE:g}')
    z_pose = LaunchConfiguration('z_pose', default='0.1')
    yaw = LaunchConfiguration('yaw', default='1.5708')

    barn_world_path = [
        worlds_dir,
        TextSubstitution(text='/world_'),
        world_idx,
        TextSubstitution(text='.world'),
    ]

    robot_state_publisher_node = Node(
        package='robot_state_publisher',
        executable='robot_state_publisher',
        name='robot_state_publisher',
        parameters=[
            {'robot_description': robot_urdf,
             'use_sim_time':use_sim_time}
        ]
    )

    joint_state_publisher_node = Node(
        package='joint_state_publisher',
        executable='joint_state_publisher',
        name='joint_state_publisher',
        parameters=[{'use_sim_time':use_sim_time}]
    )

    gazebo_server = IncludeLaunchDescription(
        PythonLaunchDescriptionSource([
            PathJoinSubstitution([
                FindPackageShare('gazebo_ros'),
                'launch',
                'gzserver.launch.py'
            ])
        ]),
        launch_arguments={
            'pause': 'false',
            'world': barn_world_path
        }.items()
    )

    gazebo_client = IncludeLaunchDescription(
        PythonLaunchDescriptionSource([
            PathJoinSubstitution([
                FindPackageShare('gazebo_ros'),
                'launch',
                'gzclient.launch.py'
            ])
        ]),
        condition=IfCondition(LaunchConfiguration('gui'))
    )

    urdf_spawn_node = Node(
        package='gazebo_ros',
        executable='spawn_entity.py',
        arguments=[
            '-entity', 'susag_updated_model',
            '-topic', 'robot_description',
            '-x', x_pose,
            '-y', y_pose,
            '-z', z_pose,
            '-Y', yaw
        ],
        output='screen'
    )

    # Front + rear scans are separate in sim; merge them into a single /scan
    # (ros2_laser_scan_merger + pointcloud_to_laserscan). Toggle with merge:=false.
    # laser_merger = IncludeLaunchDescription(
    #     PythonLaunchDescriptionSource([
    #         PathJoinSubstitution([
    #             FindPackageShare('ros2_laser_scan_merger'),
    #             'launch',
    #             'merge_2_scan.launch.py'
    #         ])
    #     ]),
    #     condition=IfCondition(LaunchConfiguration('merge'))
    # )

    return LaunchDescription([
        DeclareLaunchArgument('use_sim_time', default_value='true'),
        DeclareLaunchArgument('merge', default_value='true',
                              description='Run the front/rear laser scan merger'),
        DeclareLaunchArgument('world_idx', default_value='0',
                              description='BARN world index 0-299'),
        DeclareLaunchArgument('gui', default_value='true',
                              description='Run gzclient (false = headless server only)'),
        DeclareLaunchArgument('worlds_dir', default_value=BARN_WORLDS_DIR,
                              description='Directory with world_<idx>.world; '
                                          'defaults to the 1:1 dataset (scaled_1)'),
        robot_state_publisher_node,
        joint_state_publisher_node,
        gazebo_server,
        gazebo_client,
        urdf_spawn_node,
        # laser_merger,
    ])
